name: flutter_ads_mediation
description: A flutter package to setup, integrate and use google ads and other mediations very easily
version: 1.3.1
maintainer: Syed Waleed Shah
homepage: https://github.com/Syed-Waleed-Shah/flutter_ads_mediation

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^1.0.1
  path: ^1.8.0
  xml: ^5.1.2
